# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main
jobs:
- job: PHPUnit
  displayName: 'Run PHPUnit Tests'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePhpVersion@0
    inputs:
      versionSpec: '7.x'
      addToPath: true

  - script: composer install
    displayName: 'Install Dependencies'

  - script: vendor/bin/phpunit
    displayName: 'Run PHPUnit Tests'