# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

jobs:
- job: PHPUnit
  displayName: 'Run PHPUnit Tests'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - checkout: self

  - script: |
      php -v
    displayName: 'Check PHP Version'

  - script: |
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      php composer-setup.php
      php -r "unlink('composer-setup.php');"
    displayName: 'Install Composer'

  - script: |
      php composer.phar install
    displayName: 'Install Dependencies'

  - script: |
      php vendor/bin/phpunit
    displayName: 'Run PHPUnit Tests'